baseURL = 'https://imprs-astro-hackathon.de'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'IMPRS Astro Hackathon 2024'

disableLanguages = ["de"]

theme = 'hackatheme'

[params]
# dateStart = 2024-05-22T09:00:00+02:00 # Required
dateStart = 2024-05-21T18:00:00+02:00 # Required
dateEnd = 2024-05-24T17:00:00+02:00   # Required
dateForm = "02-01-2006"               # Required, defines date formatting style (see Hugo dateFormat)

[params.license] # Optional, but highly recommended
name = "CC-BY-SA 4.0"
#url = "https://github.com/makezurich/website/blob/master/LICENSE"

[params.styling]
backgroundHero = "/images/front/background.jpg" # Required
#logoHero = "/images/logo/logo.png"              # Required
#logoNavbar = "/images/logo/logo.png"            # Optional, leave empty to show no logo on navbar
#externalImage = "/images/externals/event-cover.png" # Optional, used for sharing meta data
themeColor = "#ffffff" # Optional
customCSS = "/css/styles.css"                       # Optional, remove/leave empty if you don't need custom styles

# Venue description
# Details are used to generate maps and schema.org meta-data
[params.venue]
name = "Haus der Astronomie"
street = "Königstuhl 18"
zipCode = "69117"
city = "Heidelberg"
state = "BW"
country = "DE"
mapboxPublicToken = "pk.eyJ1IjoidmxldWdlbGNvbXBsZW1lbnQiLCJhIjoiY2x0MmJ0NW92MG45eTJqcnptM2p5dmk1NSJ9.AXpg1DALO6Gpn76h955Phg"
mapboxStyle = "streets-v12"
mapboxZoom = 15

[params.venue.coords]
latitude = 49.3961
longitude = 8.72417

# Registration
[params.registration]
registrationForm = "https://imprs-astro-hackathon.de/start" # there be google form


[params.team]
# order = "random" # Optional, to maintain the ordering as specified, remove or set to "fixed"

[[params.team.members]]
name = "Catarina Aydar"
photo = "/images/team/catarina_aydar.png"
role = "Co-chair"

[[params.team.members]]
name = "Pietro Baldini"
photo = "/images/team/pietro_baldini.png"

[[params.team.members]]
name = "Franziska Bruckmann"
photo = "/images/team/franziska_bruckmann.png"

[[params.team.members]]
name = "Taavet Kalda"
photo = "/images/team/taavet_kalda.png"

[[params.team.members]]
name = "Cormac Larkin"
photo = "/images/team/cormac_larkin.png"
role = "Co-chair"

[[params.team.members]]
name = "Kai Lehman"
photo = "/images/team/kai_lehman.png"

[[params.team.members]]
name = "Roel Lefever"
photo = "/images/team/roel_lefever.png"

[[params.team.members]]
name = "Anirudh Ravishankar"
photo = "/images/team/anirudh_ravishankar.png"

[[params.team.members]]
name = "Florian Schulze"
photo = "/images/team/florian_schulze.png"

[[params.team.members]]
name = "Iliya Tikhonenko"
photo = "/images/team/iliya_tikhonenko.png"

[[params.team.members]]
name = "Zhang-Liang Xie"
photo = "/images/team/liang_xie.png"


[[params.social]]
title = "email"
url = "mailto:imprsastrohackathon@gmail.com"
text = "imprsastrohackathon@gmail.com"
icon = "fa-envelope"

# SEO Options: all verification codes are optional
[params.seo.verification]
google = ""
bing = ""
alexa = ""
yandex = ""

[languages]
[languages.en]
weight = 1
languageName = "English"

[[languages.en.menu.main]]
name = "Schedule"
url = "/#schedule"
weight = 2

[[languages.en.menu.main]]
name = "Venue"
url = "/#venue"
weight = 3

# [[languages.en.menu.main]]
#     name = "Challenges"
#     url = "/#challenges"
#     weight = 4

[[languages.en.menu.highlighted]]
# BEFORE
name = "Apply now!"
url = "/start"
# DURING
# name = "Getting started"
# url = "/start"

# AFTER
# name = "Projects"
# url = "/projects"
weight = 5
pre = "btn-black"
post = ""

# Hugo's Markdown rendering engine options
[blackfriday]
hrefTargetBlank = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
